<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Action names (to do)
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 59
 *  Location : locale/sk-utf8/actions.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1362'] = 'Moje nastavenia';
$lang['1305'] = 'Vymazať históriu zmien';
$lang['1295'] = 'Vrátiť';
$lang['1284'] = 'Zobraziť kľúčové slová';
$lang['1283'] = 'Zobraziť termín';
$lang['1005'] = 'Spojiť slovníky';
$lang['24_hours'] = '24hodinový časový formát';
$lang['1105'] = 'Poslať e-mail';
$lang['1095'] = 'Navrhnúť termín';
$lang['1093'] = 'Odhlásiť';
$lang['1087'] = 'Prihlásiť';
$lang['1072'] = 'Presunúť';
$lang['1036'] = 'Poslať';
$lang['1035'] = 'Náhľad';
$lang['1007'] = 'Získať HTML kód pre vyhľadávací formulár';
$lang['1006'] = 'Vymazať vyrovnávaciu pamäť (cache) hľadania';
$lang['1023'] = 'Ste si istý, že ju chcete vymazať?';
$lang['1004'] = 'Využitie vyrovnávacej pamäte';
$lang['1003'] = 'Prepočítať počet termínov v každom slovníku';
$lang['1002'] = 'Kontrola nepoužitých kľúčových slov';
$lang['1001'] = 'Poslať správu tímu podpory Glossword';
$lang['3_maintenance'] = 'Údržba';
$lang['page_refresh'] = 'Obnoviť stránku';
$lang['2_continue'] = 'Pokračovať';
$lang['3_property'] = 'Vlastnosti';
$lang['3_change'] = 'Presunúť';
$lang['3_logout'] = 'Odhlásiť';
$lang['3_send'] = 'Odoslať';
$lang['3_add_term'] = 'Pridať termín';
$lang['3_next'] = 'Ďalej';
$lang['3_register'] = 'Nové konto';
$lang['3_import'] = 'Import';
$lang['3_clean'] = 'Očistiť';
$lang['3_add_dict'] = 'Nový slovník';
$lang['3_browse'] = 'Zoznam';
$lang['3_cancel'] = 'Zrušiť';
$lang['3_save'] = 'Uložiť';
$lang['1_prevd'] = 'Predošlé %d';
$lang['1_nextd'] = 'Ďalšie %d';
$lang['1_prevpage'] = 'Predchádzajúci';
$lang['3_srch_submit'] = 'Hľadať';
$lang['3_reset'] = 'Reset';
$lang['3_down'] = 'Nižšie';
$lang['3_up'] = 'Vyššie';
$lang['3_more'] = 'Viac&#8230;';
$lang['3_export'] = 'Exportovať';
$lang['3_create'] = 'Vytvoriť';
$lang['3_edit'] = 'Upraviť';
$lang['3_remove_term'] = 'Odstrániť túto položku';
$lang['3_remove_defn'] = 'Odstrániť túto definíciu';
$lang['3_remove_trns'] = 'Odstrániť preklad';
$lang['3_remove_abbr'] = 'Odstrániť skratku';
$lang['3_remove'] = 'Odstrániť';
$lang['3_add_defn'] = 'Pridať definíciu';
$lang['3_add_trns'] = 'Pridať preklad';
$lang['3_add_abbr'] = 'Pridať skratku';
$lang['3_add'] = 'Pridať';
$lang['3_cfg'] = 'Nastavenia';
$lang['3_update'] = 'Aktualizovať';
/**
 * The end of translation file.
 */
?>