<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Virtual keyboards
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/sk-utf8/addon_virtual-keyboards.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1307'] = 'Vložte písmená oddelené čiarkou (napríklad: Ä,Á,Ă)';
$lang['2_page_virtual_keyboard_browse'] = 'Zoznam virtuálnych klávesníc';
$lang['1306'] = 'Písmená';
/**
 * The end of translation file.
 */
?>