<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Topics
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 5
 *  Location : locale/sk-utf8/addon_topics.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['2_page_topic_browse'] = 'Zoznam tém';
$lang['3_undertopic'] = 'Nadradená téma';
$lang['3_add_subtopic'] = 'Pridať podtému';
$lang['3_remove_topic'] = 'Odstrániť tému';
$lang['3_add_topic'] = 'Nová téma';
/**
 * The end of translation file.
 */
?>