<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom alphabetic order
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/sk-utf8/addon_custom-az.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1293'] = 'Štandardné zoraďovanie';
$lang['1292'] = 'list';
$lang['1291'] = 'Aktivovať profil';
/**
 * The end of translation file.
 */
?>