<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Visual themes
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 7
 *  Location : locale/sk-utf8/addon_visual-themes.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1148'] = 'Vytvorenie vizuálnej schémy';
$lang['1147'] = 'Spojiť do schémy';
$lang['1146'] = 'Vybraný štyl spôsobí, že importovaný štýl bude pridaný do existujúceho štýlu, kde prepíše všetky nastavenia.';
$lang['1145'] = 'Vstavané bloky';
$lang['1143'] = 'Titulná stránka';
$lang['1142'] = 'Všeobecné premenné';
$lang['1141'] = 'Farby';
/**
 * The end of translation file.
 */
?>