<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Abbreviation
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/sk-utf8/addon_abbr.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['id_dict_help'] = 'Slovník v ktorom sa použite skratka';
$lang['id_abbr_help'] = 'ID skratky - použite iba znaky [0-9]. Nie je možné ho neskôr zmeniť. Použije sa v <tt>&lt;(abbr|trns) lang=&quot;{Abbreviation ID}&quot;&gt;</tt>.';
$lang['id_abbr'] = 'ID skratky';
$lang['science'] = 'Vedný obor';
$lang['languages'] = 'Názvy jazykov';
$lang['linguistics'] = 'Lingvistika';
$lang['speech'] = 'Časti reči';
$lang['custom'] = 'Vlastné';
$lang['id_group'] = 'Skupina';
$lang['abbr_long'] = 'Dlhá forma';
$lang['abbr_short'] = 'Krátka forma';
/**
 * The end of translation file.
 */
?>