<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Search Log
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 1
 *  Location : locale/sk-utf8/addon_log-search.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['log_search'] = 'Záznam vyhľadávacích požiadaviek';
/**
 * The end of translation file.
 */
?>