<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Custom pages
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 3
 *  Location : locale/sk-utf8/addon_custom-pages.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1157'] = 'Odstrániť túto stránku';
$lang['1156'] = 'Nadradená stránka';
$lang['2_page_custom_pages_browse'] = 'Zoznam vlastných stránok';
/**
 * The end of translation file.
 */
?>