<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Administrative interface
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 23
 *  Location : locale/sk-utf8/admin.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1086'] = 'Aktívny predplatitelia neexistujú.';
$lang['3_subscription'] = 'Odoberanie príspevkov';
$lang['1024'] = 'Pripojiť systémové informácie na získanie najvhodnejšej reakcie.';
$lang['1022'] = 'Vyrovnávacia pamäť súborov, bajty';
$lang['1021'] = 'Počet objektov vo vyrovnávacej pamäti';
$lang['1020'] = 'Vyrovnávacia pamäť hľadania, bajty';
$lang['1019'] = 'Databáza je optimalizovaná';
$lang['1018'] = 'Nepožité kľúčové slová boli odstránené';
$lang['1017'] = 'Kľúčové slová neexistujú - nie je čo odstrániť';
$lang['1016'] = 'Ste si istý, že chcete optimalizovať databázu?';
$lang['1015'] = 'Priemerná aktuálna veľkosť po optimalizácií, bajty';
$lang['1014'] = 'Priemerná uložená veľkosť, bajty';
$lang['1013'] = 'Aktuálna veľkosť databázy, bajty';
$lang['1012'] = 'Počet indexovaných kľúčových slov po optimalizácií';
$lang['1011'] = 'Počet nepoužitých kľúčových slov';
$lang['1010'] = 'Počet kľúčových slov';
$lang['1009'] = '<p>Táto úloha skontroluje databázu pre nepoužívané kľúčové slová. Ak nejaké nájde, môžete ich odstrániť, aby ste ušetrili nejaké kilobajty na disko a čiastočne zlepšili výkon vyhľadávacieho mechanizmu.</p>

<p>Úloha významne zaťaží databázu. Dĺžka jej vykonania závisí na počet kľúčových slov. Buďte pripravený na niekoľko minútové čakanie.</p>

<p>Upozornenie: Nepoužité kľúčové slová zaberajú miesto na disku, ale na druhú stranu uľahčujú pridávanie nových termínov, pretože import nových termínov beží rýchlejšie s existujúcimi kľúčovými slovami.</p>';
$lang['1008'] = 'Kontrolovanie nepoužitých kľúčových slov';
$lang['pass_confirm'] = 'Potvrďte heslo';
$lang['pass_new'] = 'Nové heslo';
$lang['pass_current'] = 'Súčasné heslo';
$lang['2_page__'] = 'Panel nastavení';
$lang['securenote'] = 'Iba pre internú potrebu';
/**
 * The end of translation file.
 */
?>