<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Error message
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 38
 *  Location : locale/sk-utf8/err.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1348'] = 'Nebola zvolená žiadna položka.';
$lang['1347'] = 'Čas nečinnosti (v minútach): %s';
$lang['1346'] = 'Uplynulo %s minút.';
$lang['1345'] = 'Vyžaduje sa autorizácia. Používateľská relácia neexistuje alebo bola ukončená.';
$lang['1344'] = 'Ste odhlásený.';
$lang['1343'] = 'Vyžaduje sa autorizácia. Používateľská relácia neexistuje.';
$lang['1342'] = 'Používateľská relácia bola kvôli nečinnosti ukončená.';
$lang['1297'] = 'Nebol nájdený žiadny záznam.';
$lang['1255'] = 'Voľný vstup';
$lang['1254'] = 'Príliš veľa záznamov. Maximálny počet: %s. Vy ste vložili: %s.';
$lang['1090'] = 'Neplatná e–mailová adresa. Skúste znova.';
$lang['1079'] = 'Chyby';
$lang['reason_26'] = 'Termín neexistuje.';
$lang['reason_25'] = 'Termín už existuje';
$lang['reason_24'] = 'Váš účet bol aktivovaný! Prihlasovacie údaje boli odoslané na e-mail, ktorý ste uviedli na registračnej stránke.';
$lang['reason_23'] = 'Zlý aktivačný kľúč.';
$lang['reason_22'] = 'Nové heslo bolo vytvorené. Aktivačný kľúč bolo odoslaný na e-mail, uvedený na registračnej stránke.';
$lang['reason_21'] = 'Ľutujem, ale Váš je aktuálne neaktívny. Prosím, kontaktujte administrátora stránok, ktorý Vám poskytne viac informácií.';
$lang['reason_20'] = 'Uviedli ste nesprávne prihlasovacie meno alebo heslo.';
$lang['reason_19'] = 'Zadané heslo je príliš dlhé.';
$lang['reason_18'] = 'Uvedená e-mailová adresa sa už používa. Uveďte prosím inú.';
$lang['reason_17'] = 'Nie je možné poslať e-mail na %s.';
$lang['reason_16'] = 'Aktuálny účet je zablokovaný, alebo čaká na aktiváciu.';
$lang['reason_15'] = 'Zvolené prihlasovacie meno sa už používa. Vyberte iné.';
$lang['reason_14'] = 'Nové heslo nie je zhodné. Skúste znova.';
$lang['reason_13'] = 'Prístup odmietnutý';
$lang['reason_12'] = 'Taká téma neexistuje';
$lang['reason_11'] = 'Nie je možné odstrániť.';
$lang['reason_10'] = 'Súbor `%s` sa nedá nájsť.';
$lang['reason_9'] = 'Nesprávne';
$lang['reason_8'] = 'Funkcia %s nie je inštalovaná.';
$lang['reason_6'] = 'Nie je možné načítať PHP-rozšírenie `iconv` alebo `recode`.';
$lang['reason_5'] = 'Žiadne výsledky';
$lang['reason_4'] = 'Nebol nájdený žiadny slovník.';
$lang['reason_3'] = 'V téme boli nájdené slovníky.';
$lang['reason_2'] = 'V danej téme sa nachádzajú ďalšie témy.';
$lang['reason_1'] = 'Toto je posledná téma. Minimálne ešte jedna téma by mala existovať.';
$lang['reason_7'] = 'Nebol nájdený žiadny slovník.';
/**
 * The end of translation file.
 */
?>