<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Export to SQL
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 8
 *  Location : locale/sk-utf8/export_sql.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1041'] = 'Použiť hexadecimálny formát';
$lang['sql_dict_stats'] = 'Vrátane štatistiky slovníka';
$lang['sql_dict_descr'] = 'Vrátane popisu slovníka';
$lang['sql_s_and_d'] = 'Štruktúra aj dáta';
$lang['sql_keywords'] = 'Vrátane kľúčových slov pre vyhľadávací systém';
$lang['sql_droptable'] = 'Pridať &quot;DROP TABLE&quot;';
$lang['sql_data'] = 'Dáta';
$lang['sql_structure'] = 'Štruktúra';
/**
 * The end of translation file.
 */
?>