<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : General
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/sk-utf8/export.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['select_format'] = 'Vyberte formát dát';
$lang['dictdump_split'] = 'Delenie na riadky';
$lang['timeframe'] = 'Obdobie';
$lang['dictdump_fmt'] = 'Formát výstupu';
$lang['dictdump_files'] = 'Súbory';
$lang['dictdump_custom'] = 'Vlastné čísla';
/**
 * The end of translation file.
 */
?>