<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : General
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 141
 *  Location : locale/sk-utf8/global.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1379'] = 'Tlač';
$lang['1378'] = 'Zobraziť verziu tejto stránky vhodnú pre tlač.';
$lang['1377'] = 'Vložiť tento slovník do vyhľadávania vo Vašom prehliadači.';
$lang['1376'] = 'Dajte nám vedieť o akejkoľvek chybe, ktorú ste našli.';
$lang['1375'] = 'Poslať nový termín do tohoto slovníka.';
$lang['1373'] = 'Označené';
$lang['1372'] = 'Skutočne chcete označiť všetky termíny v slovníku?';
$lang['1371'] = 'Všetky termíny';
$lang['1368'] = 'sekúnd';
$lang['1367'] = 'Doba behu';
$lang['1366'] = 'Množstvo spotrebovanej pamäte';
$lang['1365'] = 'Maximálna doba behu';
$lang['mb'] = 'MB';
$lang['1363'] = 'Zmeniť ID slovníka';
$lang['1353'] = 'Odosielateľ';
$lang['1349'] = 'Prosím, zadajte vašu e-mailovú adresu alebo prihlasovacie meno. E-mail s odkazom na znovunastavenie vášho heslo bude odoslaný na e-mailovú adresu uvedenú v zázname k vášmu účtu.';
$lang['1341'] = 'Výber profilu';
$lang['1340'] = 'Letný čas/<acronym title="Daylight Saving Time">DST</acronym>';
$lang['1339'] = 'Priezvisko';
$lang['1338'] = 'Meno';
$lang['1337'] = 'Používatelia';
$lang['1336'] = 'Skratka';
$lang['1335'] = 'Slovníky';
$lang['1334'] = 'Vizuálne témy';
$lang['1333'] = 'Nastaviť kategórie';
$lang['1332'] = 'Nastavenia uložené';
$lang['1331'] = 'Komponent';
$lang['virtual_keyboard'] = 'Virtuálna klávesnica';
$lang['audio'] = 'Audio súbor';
$lang['1289'] = 'Názov profilu';
$lang['custom_az'] = 'Vlastné abecedné poradie';
$lang['1285'] = 'Osobné údaje nebudú uložené';
$lang['1282'] = 'Termín definovaný v ‘%s’';
$lang['1281'] = 'Termín začínajúci s ‘%s’';
$lang['1277'] = 'Zaujímavá stránka';
$lang['1276'] = 'Prosím, pozrite si túto stránku. Verím, že sa Vám bude páčiť
%s
%s.';
$lang['1269'] = 'Potvrdzovací kód';
$lang['1233'] = 'Nenájdené';
$lang['1214'] = 'Poštové správy';
$lang['1213'] = 'Pamätať voľbu';
$lang['1212'] = 'OK';
$lang['1185'] = 'Ďalší krok';
$lang['1183'] = 'Pokračovať ďalším krokom';
$lang['1168'] = 'Krok';
$lang['1151'] = 'Deň mesiaca';
$lang['1144'] = 'Výsledky hľadania';
$lang['custom_pages'] = 'Vlastné stránky';
$lang['3_all_time'] = 'Celé obdobie';
$lang['1115'] = 'Všetky slovníky';
$lang['1114'] = 'Ľubovoľná';
$lang['1113'] = 'Ľubovoľný';
$lang['time_gmt'] = 'Zobrazenie času GMT';
$lang['week'] = 'Týždeň';
$lang['1112'] = 'Redaktori';
$lang['1109'] = 'Váš avatar nesmie byť väčší ako %d x %d bodov.
Odoslaný avatar z Vášho počítača nesmie byť väčší ako %d KB.';
$lang['1108'] = 'Odoslať nový obrázok';
$lang['antonym'] = 'Antonymum';
$lang['1104'] = 'Vaša časová zóna';
$lang['1075'] = '<p><b>Pomocník hľadania</b></p>
<ul>
<li><p>Vyhľadávanie nerozlišuje veľkosť písme a diakritiku.</p></li>

<li><p>Štandardný vyhľadávacia metóda je ‘hľadaj vo všetkých kľúčových slovách’. 
Vyhľadávanie môžete vyladiť pomocou pridávania ďalších slov
k výraz, ktorý ste už vložili.</p></li>

<li><p>Vo svojich požiadavkách môžete kombinovať ‘*’ a ‘?’. Napríklad:</p>
<ul>
<li>požiadavka ‘ab*’ zobrazí všetky slová začínajúce písmenami ‘ab’.</li>
<li>požiadavka ‘*ca’ zobrazí všetky slová končiace na písmená ‘ca’.</li>
<li>požiadavka ‘t?me’ zobrazí položky ‘time’, ‘tome’ a ‘tame’.</li>
</ul>
&#160;
</li>
  
<li><p>Niektoré základné slová ako ‘the’, ‘is’, ‘to’ môžu byť ignorované vyhľadávacím procesom
v závislosti na nastavení slovníka.</p></li>

</ul>';
$lang['1071'] = 'Označené';
$lang['page'] = 'Stránka';
$lang['task_list'] = 'Zoznam úloh';
$lang['bug_report'] = 'Oznámiť chybu';
$lang['page_options'] = 'Nastavenie strany';
$lang['requests_total'] = 'Požiadavky celkom';
$lang['srch_3'] = 'Vyhľadávacia požiadavka';
$lang['srch_2'] = 'Nájdene v slovníkoch';
$lang['srch_-1'] = 'Vyhľadávať v termínoch a definíciách';
$lang['srch_5'] = 'požiadavky za mesiac';
$lang['srch_6'] = 'čas hľadania';
$lang['select_off'] = 'Odznačiť všetko';
$lang['select_on'] = 'Označiť všetko';
$lang['page_link_dict'] = 'Odkaz na slovník';
$lang['page_fav'] = 'Pridať k obľúbeným';
$lang['page_link_term'] = 'Odkaz na tento termín';
$lang['abbr'] = 'Skratka';
$lang['phone'] = 'Telefónne číslo';
$lang['address'] = 'Adresa';
$lang['usg'] = 'Použitie termínu';
$lang['trsp'] = 'Výslovnosť';
$lang['000'] = '-nič-';
$lang['3_password_send'] = 'Poslať heslo';
$lang['3_password_lost'] = 'Stratili ste heslo?';
$lang['2_page_22'] = 'Zmena hesla';
$lang['contact_email'] = 'Kontaktný e-mail';
$lang['contact_name'] = 'Kontaktné meno';
$lang['user_location'] = 'Krajina, mesto';
$lang['online'] = 'Zapnuté';
$lang['3_login'] = 'Prihlásenie';
$lang['2_login'] = 'Registrovaní autori';
$lang['password'] = 'Heslo';
$lang['login'] = 'Prihlasovacie meno';
$lang['fb_fill'] = 'Prosím, vyplňte nasledovný formulár';
$lang['tip014'] = '%s - aktualizované počas %d dní.';
$lang['fb_complete'] = 'Vďaka za Vašu reakciu';
$lang['total'] = 'Spolu';
$lang['terms'] = 'Termíny';
$lang['see'] = 'Pozrite tiež';
$lang['3_profile'] = 'Profil';
$lang['y_email'] = 'Váš e-mail';
$lang['array_month_short'] = 'Jan Feb Mar Apr Máj Jún Júl Aug Sep Okt Nov Dec';
$lang['array_month_decl'] = 'Január Február Marec Apríl Máj Jún Júl August September Október November December';
$lang['array_month_long'] = 'Január Február Marec Apríl Máj Jún Júl August September Október November December';
$lang['user'] = 'Používateľ';
$lang['src'] = 'Zdroj';
$lang['defn'] = 'Definícia';
$lang['syn'] = 'Synonymum';
$lang['trns'] = 'Preklad';
$lang['size'] = 'Veľkosť';
$lang['is_1'] = 'Zap.';
$lang['is_0'] = 'Neaktívovaná';
$lang['dict'] = 'Slovník';
$lang['mrk_upd'] = 'aktualizované';
$lang['mrk_new'] = 'Nový';
$lang['today'] = 'Dnes';
$lang['3_yes'] = 'Áno';
$lang['3_no'] = 'Nie';
$lang['1_nextpage'] = 'Ďalej';
$lang['lang'] = 'Jazyk rozhrania';
$lang['3_top'] = 'na začiatok stránky';
$lang['3_tomain'] = 'Domov';
$lang['L_pages'] = 'Stránky';
$lang['termsamount'] = 'Počet termínov';
$lang['descr'] = 'Popis';
$lang['printversion'] = 'Verzia pre tlač';
$lang['srch_tryall'] = 'Skúste <a href="%s">hľadať vo všetkých slovníkoch</a>.';
$lang['srch_trydefn'] = 'Skúste <a href="%s">hľadať v definíciách</a> alebo <a href="%s">vo všetkých slovníkoch</a>.';
$lang['srch_tryterm'] = 'Skúste <a href="%s">hľadať v termínoch</a>.';
$lang['srch_1'] = 'Hľadať iba v termínoch';
$lang['3_srch_submit'] = 'Vyhľadávanie';
$lang['srch_phrase'] = 'Hľadať';
$lang['srch_matches'] = 'Nájdené';
$lang['srch_strict'] = 'iba tento slovník';
$lang['srch_0'] = 'Hľadať iba v definíciách';
$lang['srch_all'] = 'Všetky slovníky';
$lang['month'] = 'Mesiac';
$lang['yesterday'] = 'Včera';
$lang['definitions'] = 'Definície';
$lang['root_topic'] = 'Hlavná';
$lang['topic_list'] = 'Zoznam tém';
$lang['9_remove'] = 'Ste si istý?';
$lang['2_success'] = 'Operácia bola úspešne ukončená.';
$lang['status'] = 'Status';
$lang['topic'] = 'Kategórie';
$lang['termsnewamount'] = 'Nové termíny';
$lang['str_page_of_page'] = 'stránka %s z %s';
$lang['str_on_page'] = 'označených termínov';
$lang['stat_dict'] = 'Slovníky';
$lang['stat_defn'] = 'Termíny';
$lang['bytes'] = 'bajty';
$lang['kb'] = 'KB';
$lang['message'] = 'Diskusný príspevok';
$lang['y_name'] = 'Vaše meno';
$lang['web_stat'] = 'Štatistika';
$lang['web_m_top10'] = 'Top 10';
$lang['web_m_fb'] = 'Spätná väzba';
$lang['term'] = 'Termín';
/**
 * The end of translation file.
 */
?>
