<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : HTML Editor
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 19
 *  Location : locale/sk-utf8/html_editor.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['ed_tagopen'] = 'otvárací tag';
$lang['ed_tagclose'] = 'ukončujúci tag';
$lang['ed_dots'] = 'bodky';
$lang['ed_degree'] = 'stupne';
$lang['ed_registered'] = 'registrovaná značka';
$lang['ed_copyright'] = 'Upozornenie o autorských právach';
$lang['ed_eurosign'] = 'znak Euro';
$lang['ed_trademark'] = 'obchodná značka';
$lang['ed_underline'] = 'Podčiarknuť';
$lang['prompt_url'] = 'Vložte URL (napríklad http://glossword.info/)';
$lang['prompt_lnk'] = 'Vložte odkaz (slovo pre vyhľadávanie v slovníku)';
$lang['prompt_txt'] = 'Vložte text odkazu (text, na ktorý bude odkaz)';
$lang['ed_nbsp'] = 'nedeliteľná medzera';
$lang['ed_quot'] = 'dvojité úvodzovky';
$lang['ed_lapki'] = 'úvodzovky 1';
$lang['ed_elochki'] = 'úvodzovky 2';
$lang['ed_p'] = 'odstavec';
$lang['ed_em'] = 'Kurzíva';
$lang['ed_bold'] = 'Tučné';
/**
 * The end of translation file.
 */
?>