<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Installation
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 85
 *  Location : locale/sk-utf8/l_install.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1253'] = 'Musí ukončiť všetky kroky, aby bola aktualizácia kompletná.';
$lang['1252'] = 'Kvôli významným zmenám v novej verzií, skript vynuluje:
1) zoznam v minulosti pridaných používateľov
2) niektoré nastavenia slovníkov
3) dátumy vytvorenia a úprav termínov
4) zoznam tém';
$lang['1251'] = 'Táto aktualizácia je určená pre verziu %s.';
$lang['1250'] = 'Uistite sa, že máte záložnú kópiu všetkých Vašich Glossword databázových tabuliek.';
$lang['1249'] = 'Aktualizácia je ukončená';
$lang['1248'] = 'Aktualizácia tabuľky <tt>‘%s’</tt>';
$lang['1247'] = 'Aktualizovanie slovníkov';
$lang['1246'] = 'Dokončovanie aktualizácie';
$lang['1245'] = 'Aktualizovanie databázy';
$lang['1244'] = 'Dôležité poznámky';
$lang['1243'] = 'Táto aktualizácia zahrňuje nasledovné:';
$lang['1242'] = 'Neexistuje spojenie s databázou.';
$lang['1241'] = 'Skontrolujte používateľa a heslo v súbore <tt>‘%s’</tt>.';
$lang['1240'] = 'Softvér nie je nainštalovaný.';
$lang['1239'] = '<a href="%s">Spustite inštalačný skript</a>.';
$lang['1238'] = 'Možné dôvody:';
$lang['1237'] = 'Nie je možné čítať nastavenia z databázy.';
$lang['1236'] = 'Softvér je odinštalovaný';
$lang['1235'] = 'Môžete odstrániť obsah priečinku <tt>‘%s’</tt>';
$lang['1234'] = 'Nájdené';
$lang['1232'] = 'Nie je možné zapísať súbor ‘%s’.';
$lang['1231'] = 'Uzamknutie programu inštalácie';
$lang['1230'] = 'Inštalácia je ukončená';
$lang['1229'] = 'Zapisovanie konfiguračného súboru.';
$lang['1228'] = 'Importovanie slovníkov';
$lang['1227'] = 'Importovanie vizuálnych tém';
$lang['1225'] = 'Importovanie tém';
$lang['1224'] = 'Vytváranie databázových tabuliek';
$lang['1223'] = 'Voliteľné rozšírenie ‘mysqli’ neexistuje.
Budete musieť aktualizovať PHP, ak chcete maximálne optimalizovať prácu s databázou.';
$lang['1222'] = 'Voliteľné rozšírenie ‘mysqli’ existuje.';
$lang['1221'] = 'Nie je možné sa pripojiť k <tt>‘%s’</tt>
s používateľom <tt>‘%s’</tt>.';
$lang['1220'] = 'Databáza <tt>‘%s’</tt> vytvorená.';
$lang['1219'] = 'Nie je možné vybrať databázu <tt>‘%s’</tt>.';
$lang['1218'] = 'Spojenie s databázou <tt>‘%s’</tt> bolo vytvorené.';
$lang['1217'] = 'Nie je možné vytvoriť novú databázu.
Pravdepodobne nemáte na to dostatočné oprávnenia.
Spoločnosti poskytujúce hosting zvyknú umožniť vytvorenie databázy pomocou hostingového ovládacie panelu.';
$lang['1216'] = 'Zadajte meno databázy.';
$lang['1215'] = 'Databáza už existuje. Zadajte prosím iné meno databázy';
$lang['1211'] = 'Cesta k priečinku so súbormi Glossword, zvyčajne <tt>‘/glossword’</tt>. 
Bez záverečnej lomky.
Nechajte prázdne, inštalujete do koreňového priečinku.';
$lang['1210'] = 'Cesta ku skriptom';
$lang['1209'] = 'Host databázy (zvyčajne localhost)';
$lang['1208'] = 'Názov databázy';
$lang['1207'] = 'Host servera alebo doménový názov';
$lang['1206'] = 'Protokol';
$lang['1205'] = 'Predpona pre databázové tabuľky';
$lang['1204'] = 'Heslo k databáze';
$lang['1203'] = 'Používateľ databázy';
$lang['1202'] = 'Konfigurácia databázy';
$lang['1201'] = 'Konfigurácia servera';
$lang['1200'] = 'Vytvoriť novú databázu (je potrebné mať práva na vytváranie databáz)';
$lang['1199'] = 'Využiť existujúcu databázu (je potrebné mať práva na vytváranie a rušenie tabuliek v konkrétnej databáze)';
$lang['1198'] = '<p>Ak nepoznáte nastavenia Vašej databázy, preverte si ich so spoločnosťou, 
ktorá vám poskytuje hostingové služby.</p>

<p class="red">Dôležité: Inštalácia zmaže všetky databázové tabuľky, 
ak použijete predponu pre tabuľky, ktorú ste už v minulosti v tejto databáze použili.</p>';
$lang['1196'] = 'Odmietnuť';
$lang['1195'] = 'Akceptovať';
$lang['1194'] = 'Akceptujete všetky podmienky licenčnej zmluvy?';
$lang['1193'] = 'Použite posuvník alebo stlačte kláves "Page down" pre pohyb v zmluve.';
$lang['1192'] = '"<p>Prosím prezrite si podmienky GNU GPL';
$lang['1191'] = 'Kontrola práv prístupu';
$lang['1190'] = 'Kontrola PHP verzie';
$lang['1189'] = 'Ukončovanie inštalácie';
$lang['1188'] = 'Konfigurovanie nastavení';
$lang['1187'] = 'Licenčná zmluva';
$lang['1186'] = '<p>Inštalácia:</p>';
$lang['1184'] = 'Nemôžete pokračovať, znovu načítajte túto stránku (stlačte F5) po oprave vyššie uvedených problémov.';
$lang['1183'] = 'Môžete pokračovať';
$lang['1182'] = 'Rozšírenie nebolo nájdené';
$lang['1181'] = 'Vyhľadávanie PHP rozšírení';
$lang['1180'] = 'Voliteľné rozšírenie ‘mbstring’ neexistuje. 
Potrebujete aktualizovať Vašu PHP verziu pre rýchlejšie indexovanie obsahu.';
$lang['1179'] = 'Rozšírenie ‘mbstring’ existuje! Indexovanie obsahu bude podstatne rýchlejšie.';
$lang['1178'] = 'Voliteľné rozšírenie `iconv` neexistuje. 
Potrebujete aktualizovať Vašu PHP verziu, aby ste mohli konvertovať znakové sady.';
$lang['1177'] = 'Rozšírenie iconv’ existuje! Môžete konvertovať znakové sady.';
$lang['1176'] = 'Povinné rozšírenie ‘%s’ neexistuje.';
$lang['1175'] = 'Povinné rozšírenie ‘%s’ existuje.';
$lang['1174'] = 'Prístup odmietnutý. Nastavte práva prístupu na <tt>‘%s’</tt> (<strong>chmod 0666</strong> by mal byť dostatočný pre súbor, <strong>chmod 0777</strong> pre priečinok)';
$lang['1173'] = 'Prístup umožnený. Povolený zápis <tt>‘%s’</tt>.';
$lang['1172'] = 'Verzia PHP použitá na tomto servery je veľmi stará. Vyžaduje sa verzia %s alebo vyššia.';
$lang['1171'] = 'PHP verzia %s';
$lang['1170'] = 'Vytváranie databázy';
$lang['1169'] = 'Kontrola systémových požiadaviek';
$lang['1167'] = '<p>Inštalácia je uzamknutá!</p>
<p>Pred spustením tohto skriptu musíte odstrániť alebo premenovať súbor <tt>‘%s’</tt>. 
Toto môžete dosiahnuť s pomocou ktoréhokoľvek FTP klienta (Filezilla, FlashFXP a ďalších).</p>';
$lang['1166'] = 'Odinštalovanie';
$lang['1165'] = 'Aktualizácia z verzií %s na %s';
$lang['1164'] = 'Nová inštalácia';
$lang['1163'] = 'Vyberte typ inštalácie';
$lang['1162'] = 'Ak máte problémy s týmto skriptom, prosím navštívte <a href="%s">stránku podpory</a>.';
$lang['1161'] = 'Vitajte v sprievodcovi nastavením %s';
/**
 * The end of translation file.
 */
?>