<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Mail messages
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 6
 *  Location : locale/sk-utf8/mail.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1350'] = 'Automatické upozornenie z portálu %s';
$lang['mail_newuser_subj'] = 'Vitajte v {SITENAME}';
$lang['mail_newpass_subj'] = 'Aktivácia nového hesla';
$lang['mail_newuser'] = '<p>Vitajte {USERNAME}.</p>
<p>Uložte si tento e-mail pre Vašu potrebu. Informácie o Vašom účte:</p>
<p>{LOGIN}: <b>{U_LOGIN}</b> <br />{PASSWORD}: <b>{U_PASSWORD}</b></p>
<p>Použite nasledujúcu URL na prihlásenie sa: <br/>{LOGIN_URL}</p>
<p>V prípade otázok napíšte na: {CONTACT_EMAIL}.</p>';
$lang['mail_newpass'] = '<p>Vitajte, {USERNAME}.</p> <p>Požiadali ste, aby Vám bolo zaslané nové heslo pre váš účet na {SITENAME}.</p> <p>Aby ste mohli použiť nové heslo, kliknite na nasledovný odkaz: <br/> {U_ACTIVATE}</p>';
$lang['2_page_user_register'] = 'Registrácia nového používateľa';
/**
 * The end of translation file.
 */
?>