<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Option text
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 198
 *  Location : locale/sk-utf8/options.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1361'] = 'Povoliť simultánny prístup';
$lang['1360'] = 'Publikovať importované termíny';
$lang['1359'] = 'Spojiť identické termíny';
$lang['1356'] = 'UTC (Univerzálny koordinovaný čas)';
$lang['1355'] = 'Povoliť úpravu vlastného profilu';
$lang['1354'] = 'Prijímať systémové udalosti';
$lang['1352'] = 'Predpona pre predmet';
$lang['1330'] = 'Pridať komponent';
$lang['1329'] = 'Pridať položku do ponuky';
$lang['1328'] = 'Ikona';
$lang['1327'] = 'Vytvoriť novú';
$lang['1326'] = 'Skryť';
$lang['1325'] = 'Vedľajšia ponuka';
$lang['1324'] = 'Hlavná ponuka';
$lang['1323'] = 'Umiestnenie';
$lang['1322'] = 'Reťazec s prekladom';
$lang['1321'] = 'Názov súboru';
$lang['1320'] = 'Publikovaný';
$lang['1319'] = 'Správca ponuky';
$lang['1318'] = 'Povoliť úpravu stránok iných používateľov';
$lang['1317'] = 'Povoliť úpravu a vytváranie vlastných stránok';
$lang['1316'] = 'Povoliť zmenu hesla';
$lang['1315'] = 'Povoliť zmenu prihlasovacieho mena';
$lang['1314'] = 'Povoliť zmenu e-mailu';
$lang['1313'] = 'Povoliť spúšťanie úloh údržby';
$lang['1312'] = 'Povoliť úpravu tém ostatných používateľov';
$lang['1311'] = 'Nepíšte znaky s diakritikou, pokiaľ nechcete ich zaradiť do zoraďovania.';
$lang['1310'] = 'Veľké písmená';
$lang['1309'] = 'Zoraďovanie';
$lang['1308'] = 'Nedokončené termíny sú označené symbolom  ‘%s’';
$lang['1304'] = 'Povoliť SEF (Search engine friendly URLs)';
$lang['1303'] = 'Režim vytvárania odkazov';
$lang['1302'] = 'Text';
$lang['1301'] = 'Alfanumerické znaky';
$lang['1300'] = 'Iba čísla';
$lang['1299'] = 'Uložiť ako súbor';
$lang['1298'] = 'Zoznam odstránených termínov';
$lang['1296'] = 'Počet dní v histórií zmien';
$lang['1294'] = 'História zmien';
$lang['1288'] = 'Ukázať';
$lang['1287'] = 'Ako zoznam';
$lang['1286'] = 'Ako tabuľku';
$lang['1280'] = 'Bez rozlišovania veľkosti písmen.';
$lang['1279'] = 'Obnoviť obrázok';
$lang['1278'] = 'Priateľov e-mail';
$lang['1275'] = 'Poslať stránku';
$lang['1274'] = 'triediť';
$lang['1273'] = 'podľa názvu';
$lang['1272'] = 'podľa dátumu';
$lang['1271'] = 'Pridať k hľadaniu';
$lang['1270'] = 'Podľa systémového nastavenia';
$lang['1268'] = 'Zoznam nedokončených termínov';
$lang['1267'] = 'Termín je dokončený';
$lang['1265'] = 'Povolené upravovanie nastavení programu';
$lang['1264'] = 'Povolené upravovanie nastavení ostatných používateľov';
$lang['1263'] = 'Povolené pridávanie termínov';
$lang['1262'] = 'Povolené upravovanie používateľských nastavení';
$lang['1261'] = 'Povolené upravovanie termínov';
$lang['1260'] = 'Povolené vytváranie slovníkov';
$lang['1259'] = 'Povolené vytváranie tém';
$lang['1258'] = 'Povolené upravovanie nastavení slovníkov';
$lang['1257'] = 'Povolené upravovanie tém';
$lang['1256'] = 'Povoliť odkazy pre termíny v tomto poli';
$lang['1197'] = 'Využívať výhody Content-Type pre XHTML 1.1-kompatibilných prehliadačov';
$lang['1158'] = 'Zlúčiť nové hodnoty s existujúcimi hodnotami';
$lang['1154'] = 'Zobraziť popis tém v katalógu';
$lang['1153'] = 'Vrátane dátumu vytvorenia a úpravy';
$lang['1152'] = 'Importované hodnoty kompletne nahradia existujúce hodnoty';
$lang['srch_topic'] = 'Hľadať v téme';
$lang['srch_dict'] = 'Hľadať v slovníku';
$lang['1150'] = 'term./sek.';
$lang['1149'] = 'Priemerná rýchlosť';
$lang['1140'] = 'Autor';
$lang['1139'] = 'Preveriť existenciu termínu';
$lang['1128'] = 'Počet dní vyhľadávacích požiadaviek vo vyrovnávacej pamäti (cache)';
$lang['1127'] = 'Očistiť vybrané slovníky po spojení';
$lang['1126'] = 'Viac položiek môžete označiť pomocou CRTL a ľavého tlačidla myši.';
$lang['1125'] = 'Vyberte jeden alebo viac slovníkov na spojenie.';
$lang['1124'] = 'Označené slovníky budú spojené do';
$lang['1123'] = 'Čítať prvý riadok';
$lang['1122'] = 'Definície sú oddeľované';
$lang['1120'] = 'Polia sú ukončované';
$lang['1119'] = 'Polia sú oddeľované';
$lang['1118'] = 'Automaticky spracovať hyperlinky';
$lang['1117'] = 'Obrázok bude zmenšený, ak je príliš veľký';
$lang['1132'] = 'Maximálna veľkosť v kilobytoch';
$lang['1130'] = 'Maximálna šírka v bodoch';
$lang['1131'] = 'Maximálna výška v bodoch';
$lang['is_abbr_long'] = 'Zobrazovať úplnú formu skratiek';
$lang['1129'] = 'Počet dní vyhľadávacích požiadaviek v záznamoch (logoch)';
$lang['period'] = 'Obdobie';
$lang['is_use_avatar'] = 'Použiť avatara';
$lang['1111'] = 'Váš aktuálny avatar';
$lang['1110'] = 'Nasledujúce typy súborov sú povolené';
$lang['srch_7'] = 'Zoznam neschválených termínov';
$lang['is_show_date_modified'] = 'Zobraziť dátum úpravy';
$lang['is_show_authors'] = 'Zobraziť zoznam redaktorov';
$lang['1103'] = 'Čas vrátane aktuálnych úprav je';
$lang['1101'] = 'Povoliť zaznamenávanie (logovanie) vyhľadávania';
$lang['1100'] = 'Povoliť zaznamenávanie (logovanie) e-mailových správ';
$lang['1099'] = 'Povoliť zaznamenávanie (logovanie) odkazujúcich stránok';
$lang['1098'] = 'Symbol použitý ako oddeľovač v "chlebových drobkoch"';
$lang['1097'] = 'Symbol použitý ako oddeľovač v  &lt;title&gt;';
$lang['1096'] = 'Počet termínov vo výsledkoch hľadania na stránke';
$lang['1084'] = 'Vyberte slovník';
$lang['1080'] = 'Predmet';
$lang['1077'] = 'Odberatelia';
$lang['1074'] = 'Pridať podstránku';
$lang['1073'] = 'Univerzálny identifikátor stránky (URI)';
$lang['1068'] = 'Cesta k exportovaným súborom';
$lang['1066'] = 'Zobraziť krátky popis slovníka v katalógu';
$lang['1065'] = 'Zobraziť ikonu v katalógu';
$lang['1064'] = 'Zobraziť počet termínov v slovníku pre katalóg';
$lang['1063'] = 'Počet slovníkov v TOP 10';
$lang['1062'] = 'Počet nedávno aktualizovaných slovníkov';
$lang['1060'] = 'Ikona súboru';
$lang['1059'] = 'Programový kód';
$lang['1058'] = 'Obsah';
$lang['1055'] = 'Citlivosť na písmená [a-z a písmená z národnej abecedy]';
$lang['1054'] = 'Citlivosť na alfanumerické znaky [a-z0-9]';
$lang['1053'] = 'Ideografické znaky';
$lang['1052'] = 'Symboly plnej a polovičnej šírky';
$lang['1051'] = 'Diakritika';
$lang['1050'] = 'Základná latinka';
$lang['1049'] = 'Citlivosť na diakritiku [ā-ž]';
$lang['1048'] = 'Citlivosť na čísla [0-9]';
$lang['1047'] = 'Filtrovať stop-slová';
$lang['1046'] = 'Filtrovať špeciálne znaky';
$lang['1045'] = 'Zobraziť text definície ako plávajúceho pomocníka pre termín';
$lang['1044'] = 'Kompatibilita s SQL verziou';
$lang['1040'] = 'Konvertovať escape sekvencie';
$lang['1039'] = 'Ponechať nezobrazujúce sa znaky (whitespace)';
$lang['1038'] = 'Vyhľadávanie nie je povolené';
$lang['1034'] = 'Chyba v dokumentácií';
$lang['1033'] = 'Chyba v preklade';
$lang['1032'] = 'Otázky ohľadom prispôsobenia';
$lang['1031'] = 'Návrhy a požiadavky';
$lang['1030'] = 'Problémy konfigurácie';
$lang['1029'] = 'Všeobecné záležitosti';
$lang['1027'] = 'Operačný systém';
$lang['1026'] = 'PHP verzia';
$lang['1025'] = 'Verzia produktu';
$lang['is_dict_as_index'] = 'Zaradiť slovník ako hlavnú stránku';
$lang['is_show_full'] = 'Zobraziť celý text definície namiesto náhľadu';
$lang['after_post_3'] = 'Otvoriť výsledky posledného hľadania';
$lang['after_post_is_save_term'] = 'Uložiť nastavenia HTML-formy';
$lang['after_post_1'] = 'Aktualizovať štatistiku slovníka';
$lang['after_post'] = 'Po&#160;uložení…';
$lang['xml_is_term_id'] = 'ID termínu';
$lang['alphabetic_order'] = 'Abecedné poradie';
$lang['fields_to_edit'] = 'Polia na úpravu';
$lang['min_srch_length'] = 'Minimálna dĺžka vyhľadávacieho reťazca';
$lang['user_notice'] = 'Poslať informáciu o registrácií';
$lang['allow_user'] = 'Prístup povolený';
$lang['allow_htmleditor'] = 'Použiť HTML-editor';
$lang['allow_leecher'] = 'Aktivovať anti-leecher';
$lang['user_dictionaries'] = 'Priradené slovníky';
$lang['date_logged'] = 'Dátum posledného prihlásenia';
$lang['date_register'] = 'Zaregistrované na';
$lang['allow_showcontact'] = 'Zobraziť kontaktné informácie';
$lang['lang_source'] = 'Jazyk termínov';
$lang['is_specialchars'] = 'Vrátane špeciálnych znakov, pri preverovaní na existenciu termínu';
$lang['admin_url'] = 'Cesta k administrátorskej stránke';
$lang['login_url'] = 'Cesta k stránke s prihlásením';
$lang['admin_host'] = 'Host administrátora';
$lang['login_host'] = 'Host prihlásenia';
$lang['admin_proto'] = 'Protokol administrátora';
$lang['login_proto'] = 'Protokol prihlásenia';
$lang['path_cache'] = 'Cesta ku cacheovaným sql požiadavkám';
$lang['path_log'] = 'Cesta k logom';
$lang['site_desc'] = 'Popis portálu';
$lang['site_name'] = 'Názov portálu';
$lang['default_lang'] = 'Štandardný jazyk';
$lang['cache_lifetime'] = 'Exspirácia cache v minútach (0-nikdy)';
$lang['cache_zlib'] = 'Použiť GZip kompresiu na uloženie/čítanie súborov v cache';
$lang['cache_is'] = 'Povoliť cache';
$lang['1133'] = 'Maximálny počet znakov pre každú definíciu v zozname termínov';
$lang['time_upd'] = 'Koľko dní je slovník označený ako aktualizovaný';
$lang['time_new'] = 'Koľko dní je slovník označený ako nový';
$lang['page_limit'] = 'Počet termínov na stránke';
$lang['sys'] = 'Systém';
$lang['enter_xml'] = 'Vložte platný XML kód';
$lang['date_modif'] = 'Posledná úprava';
$lang['date_created'] = 'Vytvorený';
$lang['dict_name'] = 'Názov práce';
$lang['announce'] = 'Krátky popis';
$lang['keywords'] = 'Kľúčové slová';
$lang['visual_theme'] = 'Vizuálna téma';
$lang['srch_selectdict'] = 'Vyberte slovník';
$lang['validate'] = 'Overiť';
$lang['overwrite'] = 'Prepísať existujúce hodnoty novými hodnotami';
$lang['till_time'] = 'Kam';
$lang['from_time'] = 'Od';
$lang['dictdump_list'] = 'Zo zoznamu';
$lang['allow_letters'] = 'Zobraziť panel s abecedou (A-Z)';
$lang['sysname'] = 'Názov tabuľky v databáze';
$lang['options'] = 'Voľby';
$lang['ed_xref'] = 'umiestniť odkaz na termín';
/**
 * The end of translation file.
 */
?>