<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Current status (present tense)
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 11
 *  Location : locale/sk-utf8/status.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['2_page_custom_az_browse'] = 'Prezeranie profilov';
$lang['2_page_term_viewkeywords'] = 'Prezeranie kľúčových slov hľadania';
$lang['2_page_term_browse'] = 'Zoznam termínov';
$lang['1107'] = 'Prezeranie profilu';
$lang['2_page_32'] = 'Prezeranie  aktuálneho predplatného';
$lang['2_page_sys_maintenance'] = 'Údržba systému';
$lang['2_page_user_browse'] = 'Zoznam používateľov';
$lang['2_page_17'] = 'Aktualizácia termínu';
$lang['2_page__srch'] = 'Hľadanie...';
/**
 * The end of translation file.
 */
?>