<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Dialog title
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 18
 *  Location : locale/sk-utf8/tdb.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1351'] = 'Nastavenie e-mailu';
$lang['1160'] = 'Populárne vyhľadávacie požiadavky';
$lang['1159'] = 'Posledné vyhľadávacie požiadavky';
$lang['1116'] = 'Nastavenie avatara';
$lang['1061'] = 'Nastavenie obsahu';
$lang['1056'] = 'Nastavenie interného vyhľadávacieho systému';
$lang['1138'] = 'Systémové nastavenia';
$lang['sect_edit_dict'] = 'Nastavenia prvkov slovníka';
$lang['1136'] = 'Vizuálne nastavenia';
$lang['srch_phrase_edit'] = 'Hľadať termín na úpravu';
$lang['user_profile'] = 'Profil';
$lang['user_reginfo'] = 'Registračné informácie';
$lang['sect_cache'] = 'Nastavenie vyrovnávacej pamäte';
$lang['sect_login'] = 'Nastavenie prihlasovania';
$lang['1135'] = 'Názvy ciest';
$lang['1137'] = 'Všeobecná konfigurácia';
$lang['tpl_list'] = 'Zoznam šablón';
$lang['catalog'] = 'Katalóg';
/**
 * The end of translation file.
 */
?>