<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Table header title
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 21
 *  Location : locale/sk-utf8/tht.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['1358'] = 'Systémové súbory';
$lang['1357'] = 'Položka do ponuky';
$lang['1266'] = 'Zálohovanie';
$lang['1106'] = 'Kontaktné informácie';
$lang['1037'] = 'Práva prístupu';
$lang['1028'] = 'Verzia databázy';
$lang['r_term_updated'] = 'Nedávno aktualizované termíny';
$lang['recent'] = 'Nedávno pridané';
$lang['action'] = 'Činnosť';
$lang['r_term_newest'] = 'Nové termíny';
$lang['r_dict_updated'] = 'Nedávno aktualizované slovníky';
$lang['2_tip'] = 'Informácie';
$lang['2_page_dict_browse'] = 'Zoznam slovníkov';
$lang['order'] = 'Zoradenie';
$lang['title_search'] = 'Vyhľadávanie termínov';
$lang['th_5'] = 'Posledné publikované dáta';
$lang['th_4'] = 'Celkom hitov';
$lang['th_3'] = 'Priemerný počet hitov';
$lang['th_1'] = 'Názov';
$lang['r_dict_averagehits'] = 'Najpopulárnejšie slovníky';
$lang['r_dict_newest'] = 'Nedávno pridané slovníky';
/**
 * The end of translation file.
 */
?>