<?php
/**
 *  DO NOT EDIT. Alteration of this file may cause the Glossword to malfunction.
 *  For any changes, please, contact translators.
 *  Translation file generated by Translation Kit (http://tkit.info/)
 *  © 2002-2007 Dmitry Shilnikov <dev at glossword dot info>
 *  ------------------------------------------------------
 *  Project  : Glossword
 *  Topic    : Tool tip
 *  Language : Slovak
 *  Charset  : UTF-8
 *  Phrases  : 29
 *  Location : locale/sk-utf8/tol.php
 *  Created  : 26 Apr 2008, 00:36
 *  ------------------------------------------------------
 *  Translation created by:
 *      - Dmitry N. Shilnikov <dev at glossword.info>
 *      - Zdenko Podobny <zdenop at gmail.com>
 */
$lang['tip032'] = 'Vlastný PHP kód, ktorý sa má spustiť na danej stránke. Napríklad:
<ul class="noindent">
<li><tt>print_r( $arV );</tt> - zobraziť všetky nastavenia strany.</li>
<li><tt>print_r( $sys );</tt> - zobraziť všetky systémové nastavenia.</li>
<li><tt>$oTpl->addVal( \'v:custom_var\', \'123\');</tt> - pridať text `123\'
if <tt>{%v:custom_var%}</tt> je prezentovaný v obsahu stránky 
alebo v HTML šablónach.</li>
</ul>';
$lang['tip031'] = 'Identifikátor strany, použije sa pri zapnutom <tt>mod_rewrite</tt>.';
$lang['tip030'] = 'Obsah stránky. Možné premenné sú:
<ul class="noindent">
<li><tt>{%block:page_descr%}</tt> - krátky popis stránky;</li>
<li><tt>{%subpages_cnt%}</tt> - počet vložených stránok;</li>
<li><tt>{%subpages_ul%}</tt> - zoznam vložených stránok, iba nadpisy.</li>
<li><tt>{%subpages_dl%}</tt> - zoznam vložených stránok so skráteným popisom;</li>
</ul>';
$lang['tip029'] = 'Krátky popis stránky. Použije sa v zozname vložených stránok.';
$lang['tip028'] = 'Názov stránky';
$lang['tip027'] = 'Konvertovať escape sekvencie na znaky. \t sa skonvertuje na &amp;#009;.';
$lang['tip026'] = 'Ponechať netlačiteľné (whitespace) znaky, &amp;#009; bude uložený.';
$lang['tip025'] = 'Vložte meno, pod ktorým chcete pracovať. Podporované sú aj nelatinkové znaky.';
$lang['tip024'] = 'Heslo je potrebné potvrdiť len v tom prípade, ak ste ho vyššie zmenili.';
$lang['tip023'] = 'Nové heslo je potrebné zadať len v prípade, že chcete zmeniť to aktuálne.';
$lang['tip022'] = 'Musíte potvrdiť aktuálne heslo, ak ho chcete zmeniť.';
$lang['tip021'] = 'Slovník &#8594; Zoznam &#8594; Vyberte slovník zo zoznamu &#8594; Upraviť &#8594; Kontrola &quot; Publikovať slovník &quot; potom kliknite na &quot;Uložiť&quot;';
$lang['tip020'] = 'Slovník &#8594; Zoznam &#8594; Vyberte slovník zo zoznamu &#8594; Pridať termín &#8594; Vyplňte formulár a kliknite na &quot;Uložiť&quot;.';
$lang['tip019'] = 'Slovník &#8594; Pridať &#8594; Vyplňte formulár a kliknite na &quot;Uložiť&quot;.';
$lang['tip016'] = 'Vytvoriť nový slovník';
$lang['tip015'] = '%s - nové za posledných %d dní.';
$lang['tip013'] = 'Dodatočná kontrola termínov so špeciálnymi znakmi р !, @, #, $ a pod.';
$lang['tip012'] = 'Preveriť existenciu termínov a definícií.';
$lang['tip011'] = 'Preveriť XML syntax';
$lang['tip010'] = 'Názov slovníka';
$lang['tip009'] = 'Vložte anotáciu pre katalóg';
$lang['tip008'] = 'Vložte popis slovníka pre titulnú stránku.';
$lang['tip007'] = 'Vložte kľúčové slová oddelené čiarkou (,). Použijú sa ako META-tagy on stránkach slovníka.';
$lang['tip006'] = 'Vyberte tému z katalógu.';
$lang['tip005'] = 'Vyberte jazyk pre rozhranie slovníka. Pre viac jazykové slovníky vyberte štandardný systémový jazyk.';
$lang['tip004'] = 'Vyberte katalóg s HTML šablónami, ktorými bude spracovaný slovník';
$lang['tip001'] = 'Exportovať hodnoty, ktoré bolo pridané alebo zmenené počas určeného obdobia.';
$lang['tip003'] = 'Zadajte názov databázovej tabuľky slovníka. Použite iba znaky [0-9a-z]. Neskôr ho nebude možné zmeniť.';
$lang['tip002'] = 'Oddeľovať termíny novým riadkom.';
/**
 * The end of translation file.
 */
?>