name: PHP lint

on:
  push:
    branches: [ "stand-alone" ]
  pull_request:
    branches: [ "stand-alone" ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false     
      matrix:  
        php-version: ['7.2', '8.2']
        experimental: [false]

    steps:
      -   # https://github.com/actions/checkout
        name: Checkout code
        uses: actions/checkout@v4
        
      - uses: php-actions/composer@v6

      - name: Check PHP syntax errors
        uses: overtrue/phplint@9.1.0
        with:
          path: 1.8
          options: --exclude=*.log

