name: PHP lint

on:
  # push:
    # branches: [ "stand-alone" ]
  # pull_request:
    # branches: [ "stand-alone" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2'] # '7.2',
        experimental: [false]

    steps:
      -   # https://github.com/actions/checkout
        name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --prefer-dist --no-interaction
          php_version: ${{ matrix.php-version }}
          php_extensions: xml
          version: 2

      -   # https://getcomposer.org/doc/06-config.md#platform
        name: Setup Composer Platform
        run: |
          composer config platform.php ${{ matrix.php-version }}

      - name: Check PHP syntax errors
        uses: overtrue/phplint@9.1.0
        with:
          path: 1.8
          options: --exclude=*.log

